---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH